@startuml Storage Net, Use Case, Delivery Arrange

left to right direction

actor "Manager" as manager
actor "Administrator" as admin
actor "Source" as source

usecase "Arrange an external delivery" as external_delivery

package System {
  usecase "Request the delivery to storage A" as request_delivery

  usecase "Approve the delivery request" as approve
  usecase "Reject the delivery request" as reject

  usecase "Notify" as notify
}

manager --> external_delivery
external_delivery --> source

manager --> request_delivery
request_delivery --> admin

admin --> approve
admin --> reject

approve --> notify
reject --> notify

notify --> source

@enduml